import { Platform, StyleSheet } from 'react-native';

export const colors = {
  ink: '#173042',
  inkMuted: '#5D7380',
  teal: '#087E8B',
  tealDark: '#05616B',
  tealSoft: '#DDF3F2',
  mint: '#EAF8F4',
  coral: '#E76F51',
  coralDark: '#B94732',
  amber: '#F3B562',
  amberSoft: '#FFF4DF',
  redSoft: '#FDE9E6',
  red: '#B9382D',
  line: '#D7E5E6',
  paper: '#FAFCFB',
  white: '#FFFFFF',
  navy: '#173042',
  shadow: '#143642',
};

export const radii = { sm: 10, md: 16, lg: 24, pill: 999 };

export const shared = StyleSheet.create({
  flex: { flex: 1 },
  screen: { flex: 1, backgroundColor: colors.paper },
  container: { width: '100%', maxWidth: 760, alignSelf: 'center', paddingHorizontal: 20 },
  scrollContent: { paddingBottom: 120 },
  title: { color: colors.ink, fontSize: 30, lineHeight: 37, fontWeight: '800', letterSpacing: -0.5 },
  h2: { color: colors.ink, fontSize: 20, lineHeight: 27, fontWeight: '800' },
  body: { color: colors.inkMuted, fontSize: 16, lineHeight: 24 },
  caption: { color: colors.inkMuted, fontSize: 13, lineHeight: 19 },
  label: { color: colors.ink, fontSize: 15, fontWeight: '700', marginBottom: 8 },
  input: {
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.line,
    borderRadius: radii.sm,
    color: colors.ink,
    fontSize: 17,
    minHeight: 54,
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === 'web' ? 12 : 10,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.teal,
    borderRadius: radii.sm,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: 18,
  },
  primaryButtonText: { color: colors.white, fontSize: 17, fontWeight: '800' },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.tealSoft,
    borderRadius: radii.sm,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 16,
  },
  secondaryButtonText: { color: colors.tealDark, fontSize: 16, fontWeight: '800' },
  card: {
    backgroundColor: colors.white,
    borderColor: colors.line,
    borderRadius: radii.md,
    borderWidth: 1,
    padding: 18,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  row: { alignItems: 'center', flexDirection: 'row' },
  errorText: { color: colors.red, fontSize: 15, lineHeight: 22, textAlign: 'center' },
});